namespace TaskService.Application.Interfaces;

/// <summary>
/// Where uploaded files are kept. Storage keys are generated by the caller and
/// never derived from a client-supplied name, so an implementation can treat a
/// key as a trusted, well-formed relative path.
/// </summary>
public interface IFileStorage
{
    System.Threading.Tasks.Task SaveAsync(string storageKey, Stream content, CancellationToken cancellationToken = default);
    System.Threading.Tasks.Task<Stream?> OpenReadAsync(string storageKey, CancellationToken cancellationToken = default);
    System.Threading.Tasks.Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default);
}
